apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-encora-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-encora-gateway
  template:
    metadata:
      labels:
        app: spring-boot-encora-gateway
    spec:
      containers:
        - name: spring-boot-encora-gateway
          image: rolandojavier13/spring-boot-encora-gateway:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SERVICE_EXTERNAL
              value: spring-boot-encora-mibanco-challenge:8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-encora-gateway
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: spring-boot-encora-gateway
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-encora-gateway
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /business-exchange
            pathType: Prefix
            backend:
              service:
                name: spring-boot-encora-gateway
                port:
                  number: 8090
